apiVersion: batch/v1
kind: Job
metadata:
  name: sleep-hook
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: sleep
          image: busybox
          command:
            - sh
            - -c
            - |
              max={{ .Values.sleepSecondsMax | default 30 }}
              min=3
              sleep $((RANDOM % (max - min + 1) + min))
